name: confluence-7.19-mysql-stack

services:
  mysql:
    image: mysql:lts-oraclelinux9-confluence
    restart: no
    ports:
    - 3306:3306
    environment:
    - "MYSQL_ROOT_PASSWORD=my-secret-pw"
    - "MYSQL_DATABASE=confluence"
    - "MYSQL_USER=confluence"
    - "MYSQL_PASSWORD=confluence"
    volumes:
    - mysql_data_vol:/var/lib/mysql
    networks:
    - confluence_network

  confluence:
    image: atlassian/confluence:7.19-ubuntu-jdk11-mysqlj
    restart: no
    ports:
    - 8090:8090
    - 8091:8091
    volumes:
    - confluence_data_vol:/var/atlassian/application-data/confluence
    networks:
    - confluence_network
    depends_on:
      mysql:
        condition: service_started

volumes:
  confluence_data_vol:
  mysql_data_vol:

networks:
  confluence_network: {}